### ISSUE TITLE
AWS Cloud9 Different Instructions

### ISSUE THREAD

**Issue by ackerm44** [learn-co-curriculum/rack-intro#10]
I just started utilizing the AWS Cloud9 and it appears that Cloud9 will only listen to port 8080 , 8081 and 8082.  I had to utilize this command in the terminal:  rackup -p 8080 -o 0.0.0.0 and was able to see the preview of the page only then. 

Not sure if this is worth mentioning in the instructions or not.  Thanks!

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention.

As always thank you for contributing!
