### ISSUE TITLE
Instructions provided do not work with Learn IDE.

### ISSUE THREAD

**Issue by Jenhop8786** [learn-co-curriculum/rack-intro#11]
I was not able to preview the site with address given or with rack configs provided, using Learn IDE.  

<img width="686" alt="screen shot 2018-02-09 at 07 47 11" src="https://user-images.githubusercontent.com/13800852/36036106-cf74c6ae-0d6d-11e8-9323-34e0844ecad0.png">

<img width="735" alt="screen shot 2018-02-09 at 07 46 02" src="https://user-images.githubusercontent.com/13800852/36036096-c5c898d8-0d6d-11e8-8f20-ada989553b2a.png">

<img width="604" alt="screen shot 2018-02-09 at 07 45 47" src="https://user-images.githubusercontent.com/13800852/36036078-ba09fcd0-0d6d-11e8-8998-5ca91b63fb94.png">

<img width="529" alt="screen shot 2018-02-09 at 07 43 41" src="https://user-images.githubusercontent.com/13800852/36036010-85ac5bd6-0d6d-11e8-8da7-fb2452a1d534.png">

**Comment by curiositypaths** [comment]
Hi there,

The `159.203.101.28:30001` was just an example IP Address:Port combination. In your instance, the IP Address:Port was `165.227.16.205:49762`. Each time you run the Learn IDE you might receive a different IP Address:Port combination.

As always thank you for contributing.
