### ISSUE TITLE
It is not explicit about the application file

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/rack-intro#13]
The paragraph from the README: "We first create a Rack::Response object, then add some text "Hello, World" to the body, and complete the response with the #finish method. By default, Rack sets our status codes and headers. Don't worry about the env input. This holds all of the request info in it and we will use it later!" as well as the paragraph following the code, do not explicitly say where you've put this in the repo.  

I recommend adding "...create a Rack::Response object, written in the application.rb file, then add..." as a simple fix to prevent wasted time with confusion or looking for it.

**Comment by sgharms** [comment]
Agreed! Changed.
