### ISSUE TITLE
Learn IDE special instructions

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/rack-intro#14]
My computer got the "This site cannot be reached" error message even with the Learn IDE workaround that was suggested of inputting the IP address directly.

**Comment by sgharms** [comment]
By the time you're here, I think you should probably be working in a local environment. Is there some context where you're still using the Learn IDE?

**Comment by sgharms** [comment]
@regilfillan 

I'm going to close this out pending update from you. If you can help contextualize where you're hitting this problem, we'll try to clarify.

Steven
