### ISSUE TITLE
Readme no longer contains information regarding application.rb

### ISSUE THREAD

**Issue by twwright** [learn-co-curriculum/rack-intro#17]
It looks like the tests are asking to do something that is no longer described in the `readme` file. Looking at issue #13 it seems that there was some verbiage removed from the lesson which would give more information about how to pass this particular lab. There is no information given related to how to use Rack::Response or what is happening at all in the `application.rb` file, but the test still expects us to update that file to pass.

Consider updating tests to reflect new readme, or else re-insert information regarding Rack::Response that was removed from line 30 of [this commit](https://github.com/learn-co-curriculum/rack-intro/commit/3d23e21e2cf6e6d6a83b2b624582a187f118e9ca).

**Comment by twwright** [comment]
It seems like information about `Rack::Response` was moved to the next lab. Consider updating the tests to either remove that requirement or restructure it to check the `my_server.rb` file for the `Hello, my name is` info.

**Comment by ihollander** [comment]
Fixed by https://github.com/learn-co-curriculum/rack-intro/commit/714a75860caf5ac559bbe949ab9652336bbaf1aa
