### ISSUE TITLE
Missing gem: rack-test

### ISSUE THREAD

**Issue by zachnewburgh** [learn-co-curriculum/rack-intro#4]
The repo is missing the rack-test gem. Students will need to run `gem install rack-test` in order for learn commands to execute.

**Comment by victhevenot** [comment]
hey @zachnewburgh, did you find that you needed the `rack-test` gem in order for the tests to run at all when you entered `learn`? or for the lights to change?

**Comment by zachnewburgh** [comment]
Hi @vicfriedman, yes, I did. Not sure if I'm the only person to have faced that issue, but I kept getting an error message saying that I needed it – hope that's helpful!
